#!/usr/bin/env python3
"""Regenerates wyrm-sources.js by bundling the wyrm/ Python package
(lexer, parser, AST, environment, interpreter, async adapter) as a JSON
blob that script.js writes into Pyodide's virtual filesystem at boot.

Run this after editing any file under wyrm/ so the browser build stays
in sync:

    python3 build_sources.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
WYRM_DIR = os.path.join(HERE, "wyrm")
OUT_PATH = os.path.join(HERE, "wyrm-sources.js")


def main():
    sources = {}
    for fname in sorted(os.listdir(WYRM_DIR)):
        if fname.endswith(".py"):
            with open(os.path.join(WYRM_DIR, fname), encoding="utf-8") as f:
                sources[fname] = f.read()

    js_content = (
        "// AUTO-GENERATED by build_sources.py - do not edit manually\n"
        "window.WYRM_SOURCES = " + json.dumps(sources) + ";\n"
    )

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Bundled {len(sources)} files into {OUT_PATH} "
          f"({os.path.getsize(OUT_PATH)} bytes)")


if __name__ == "__main__":
    main()
